### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by lahovniktadej**
Summary of changes:
1. Updated ``README.md``
2. Sphinx documentation

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Brilliant, thanks!

**Comment by firefly-cpp** [comment]
@lahovniktadej, please check CI errors. It seems that deps are not consistent.

**Comment by lahovniktadej** [comment]
@firefly-cpp, I've updated ``poetry.lock``, which should resolve the CI errors. The workflow is awaiting approval.

**Comment by firefly-cpp** [comment]
@all-contributors please add @lahovniktadej for docs, tutorial

**Pull request merged**
